### ISSUE TITLE
Always require arrow function parens

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/eslint-config-nrk#12]
In my experience, it’s easier to read arrow functions when the parens are used:

```js
const SomeComponent = (state) => (
  <div>{state.title}</div>
)
```

The following is slightly harder to read:

```js
const SomeComponent = state => (
  <div>{state.title}</div>
)
```

In the latter case, the `state` argument can be misinterpreted as being used in the context of assignment or comparison.

I’ll make a pull request adding `"arrow-parents": "always"`.

**Comment by janerikbr** [comment]
Agreed, this improves readability and is more concise.
