### ISSUE TITLE
Add badges for travis, coveralls and npm

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/eslint-config-nrk#16]
To enable this, we need to setup [Travis CI](https://travis-ci.org/) and [Coveralls](https://coveralls.io/) accounts.

**Comment by mariuslundgard** [comment]
Here’s the npm badge:

![npm badge](https://img.shields.io/npm/v/eslint-config-nrk.svg?style=flat)

**Comment by akselnordal** [comment]
@mariuslundgard have you setup travis/coveralls accounts? If you want to connect it to the opensource@nrk.no distribution list, just add it as the account owner and I can confirm via mail. If needed, you may be added to the distribution list as well. cc @oyvindholmstad

**Comment by mariuslundgard** [comment]
@akselnordal Yes, I was able to add it through the organization membership. Sorry for uneeded @'ing. However, I can't figure out where the email setting in Travis CI is located.
