### ISSUE TITLE
Disqus: "Node common" no-sync, default value

### ISSUE THREAD

**Issue by cristobal** [nrkno/eslint-config-nrk#34]
Burde dette ikke være optional eller heller vært satt til `1` warning, i stedet.
På rule siden står det:

> In some contexts, using synchronous operations is okay (if, as with ESLint, you are writing a command line utility).  

By default så er den satt til `off` i [eslint:recommended](https://github.com/eslint/eslint/blob/master/conf/eslint.json).

**Comment by janerikbr** [comment]
Foreslår å justere denne fra "error" til "warn" - `async` er vel som regel er å foretrekke? Som en heads up på at dette bør man kanskje gjøre annerledes?
