### ISSUE TITLE
Disqus: Stylistic operator-linebreak rule

### ISSUE THREAD

**Issue by cristobal** [nrkno/eslint-config-nrk#35]
Kan ikke si meg helt enig i valget med [`operator-linebreak`](http://eslint.org/docs/rules/operator-linebreak) og vil heller hatt `off` by default, slik det er i `eslint:recommended`.
Så kan man heller tvinge fram stylistic per prosjektet om man vil enforce.
Om man bruker `+` før eller etter linje er ikke så farlig.

**Comment by janerikbr** [comment]
Jeg synes det høres ut som en god idé å skru av `operator-linebreak`. Fint å slippe feil når man bruker ternary og har `?`og `:` på separate linjer også.

**Comment by cristobal** [comment]
Opprette PR https://github.com/nrkno/eslint-config-nrk/pull/36
