### ISSUE TITLE
Disqus: Indent rules for aligned variable declarations

### ISSUE THREAD

**Issue by tolu** [nrkno/eslint-config-nrk#37]
Would like to know your thought in extending the indent rules with :
`"VariableDeclarator": { "let": 2, "const": 3 }`

This would allow us to align variable declarations, which in my opinion makes them easier to read.
With the current rule set this is allowed.
```js
let someVariable,
  anotherVariable;
```

With the proposed update, the above would result in an error whilst this would work:
```js
let someVariable,
    anotherVariable;
```

And for consts:
```js
const someVariable,
      anotherVariable;
```

**Comment by cristobal** [comment]
I agree on the topic, usually myself i turn of the `no-multi-spaces` .
However i have switched to always enforce the `one-var-declaration-per-line` style.

**Comment by mariuslundgard** [comment]
In my opinion, multiple `let`/`const` declarations is easier to read and maintain, e.g.:

```js
const someVar = 1
const otherVar = 2
let didChange = false
```

Using this style, indenting is not an issue. Like @cristobal says, using `one-var-declaration-per-line` enforces this.

@tolu: What are the benefits of grouping var declarations?

**Comment by eirikbacker** [comment]
Agree with @mariuslundgard

**Comment by tolu** [comment]
Well I'm not arguing for whether or not to use one or multiple variable statements.

Simply that if you prefer multiple,  aligning the names improves readability.

And if everyone agrees that one variable declaration per line is preferred, then I suggest that be turned on by default.

**Comment by mariuslundgard** [comment]
OK, I get it now, your OP is a good idea. I’ll make a PR.

**Comment by eirikbacker** [comment]
Or should we rather include one-var-declaration-per-line? :)

**Comment by mariuslundgard** [comment]
Yes, we should enforce `one-var` and `one-var-declaration-per-line` @eirikbacker. PR #38 fixes that.

However, consumers are free to override `eslint-config-nrk` in their own `.eslintrc`.

In @tolu's case, he can now (if @janerikbr merges the PR) add:

```json
  "rules": {
    "one-var": ["error", "always"],
    "one-var-declaration-per-line": ["error", "always"]
  }
```

Since `"VariableDeclarator": { "let": 2, "const": 3 }` has been added to the `indent` rule, he won't get indentation errors when writes code like this:

```
const i = 1,
      x = 2;
```
