### ISSUE TITLE
Don't assume usage of (Babel) transpiler

### ISSUE THREAD

**Issue by janerikbr** [nrkno/eslint-config-nrk#4]
The rule `strict` within `base.js` assumes that Babel inserts `"use strict"`, and is thus set to

`"strict": [2, "never"]`

Default config should not make assumptions about transpiler, so this rule should probably be set to

`"strict": [2, "always"]`

**Comment by mariuslundgard** [comment]
Would a solution to this be to enforce strict mode only for ES5? (Requires adding ES5 support.)

**Comment by mariuslundgard** [comment]
Closing because it's such a minor (and vague) issue.
