### ISSUE TITLE
Publish v5.0.0 to npm

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/eslint-config-nrk#40]
And provide changelog here:
https://github.com/nrkno/eslint-config-nrk/releases/new?tag=v5.0.0

**Comment by mariuslundgard** [comment]
See https://github.com/nrkno/eslint-config-nrk/releases/tag/v4.0.0 for reference.

**Comment by mariuslundgard** [comment]
Also, we should always have another developer than the one who wrote the code test it and merge any PR to this repo. The code looks sound and I trust you know what you’re doing @cristobal, but let’s make this the standard process.

+1 for contributing!

**Comment by cristobal** [comment]
@mariuslundgard i totally agree but this branch and PR has been here lying to long. I talked with @janerikbr about this release today. 

The next is scheduled to be up and going in 2-3 weeks.
We also talked about a more proper build schedule.

**Comment by mariuslundgard** [comment]
Ok, cool, good that you guys talked offline :)

PS. I enabled branch protection on `master` to prevent this in the future. Admins may change it if that's too strict.

**Comment by cristobal** [comment]
@mariuslundgard that's ok 👍

**Comment by cristobal** [comment]
Will fill in the Changelog my thought also is that we have a [CHANGELOG.md](http://keepachangelog.com/) in the repo?

**Comment by mariuslundgard** [comment]
Fine by me 👍

**Comment by cristobal** [comment]
@mariuslundgard  changelog updated

**Comment by mariuslundgard** [comment]
That's a really good changelog! Thanks for the effort.

Now if you do a `npm publish` on the master branch we/you can close this issue :)

**Comment by cristobal** [comment]
Fikk følgende feilmeilding:

```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code E403

npm ERR! you do not have permission to publish "eslint-config-nrk". Are you logged in as the correct user? : eslint-config-nrk
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/n24651/Projects/NRK/eslint-config-nrk/npm-debug.log
```
