### ISSUE TITLE
Add max-lines rule?

### ISSUE THREAD

**Issue by bratberg** [nrkno/eslint-config-nrk#41]
Force developers to at least consider splitting huge files into modules?
http://eslint.org/docs/rules/max-lines

**Comment by cristobal** [comment]
We released version 5.0.0 yesterday that raises an warning when your file exceeds 500 lines of code.
It's out on https://www.npmjs.com/package/eslint-config-nrk now fresh of the boat ;)

**Comment by bratberg** [comment]
Awesome! (Weird that I couldn't find the rule when i searched for it though - https://github.com/nrkno/eslint-config-nrk/search?utf8=%E2%9C%93&q=%22max-lines%22&type=Code)

**Comment by cristobal** [comment]
@bratberg ah no you are right here i am wrong.
Will add it to the rule set.
We raised an warning on http://eslint.org/docs/rules/max-lines
