### ISSUE TITLE
Consider making stylistic issues optional

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/eslint-config-nrk#42]
After today’s long discussion on Slack, here's a summary:

* Consider making stylistic issues optional (see https://github.com/nrkno/eslint-config-nrk/blob/master/rules/stylistic-issues.js).
* Consider using `prettier` for stylistic issues. And if so, consider basing the ruleset on `eslint-config-prettier`.

**Comment by svenanders** [comment]
So, someone needs to create that ```prettier``` ruleset. Maybe @popeindustries could volunteer to do that :1st_place_medal:

**Comment by mariuslundgard** [comment]
Here it is: https://www.npmjs.com/package/eslint-config-prettier

**Comment by popeindustries** [comment]
@mariuslundgard any idea how we could make Prettier the default, then ignore it if you want to opt into the nrk style rules? Or would we have to choose a style rule set: Prettier or NRK?

**Comment by cristobal** [comment]
I agree on this issue however for the next update it's about getting in sync with latest eslint changes.
Then i think we could startup the the prettier stuff. I'm guessing two milestones ahead.

So we can use some time to plan and agree on the base styles for prettier.
Also not sure if we use prettier if it should go here or in a separate repo?

**Comment by mariuslundgard** [comment]
@popeindustries I believe it's possible to have `eslint-config-prettier` as the default style rules, and an optional `nrk/rules/stylistic-issues`, but then `nrk/rules/stylistic-issues` would have to override prettier's. It's a little bit ugly IMO. I'm more for going all in on `prettier` if we decide we like it.

@cristobal That's fine, we can branch out and play with `prettier`, and possibly rebase later on. No rush :) `prettier` is still in beta and apparently changes a lot still.

**Comment by mariuslundgard** [comment]
Check it out in the browser:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20Boo%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20Please%20state%20your%20%3Cb%3Ename%3C%2Fb%3E%20and%20%3Cb%3Eoccupation%3C%2Fb%3E%20for%20the%20board%20of%20directors.%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%5Cnconst%20Yay%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20Please%20state%20your%20%3Cb%3Ename%3C%2Fb%3E%20and%20%3Cb%3Eoccupation%3C%2Fb%3E%20for%20the%20board%5Cn%20%20%20%20%20%20of%20directors.%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by popeindustries** [comment]
I'm just playing around with the 2 configs in the same project, and it seems fine to override `nrk` with `prettier`. I'm not sure how inefficient it is to have so many overrides, but it's possible to leave the `nrk` ruleset unchanged and use Prettier.

**Comment by mariuslundgard** [comment]
Ok, interesting. Can you post the `.eslintrc` here?

**Comment by svenanders** [comment]
This works fine:
```
{
  "root": true,
  "extends": [
    "nrk",
    "plugin:inferno/recommended",
    "prettier"
  ],
  "plugins": [
    "inferno",
    "prettier"
  ],
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "node": true
  },
  "parser": "babel-eslint",
  "rules": {
    "comma-dangle": "off",
    "inferno/prop-types": "off",
    "inferno/display-name": "off",
    "no-undef": "off",
    "prettier/prettier": "error"
  }
}
```
but I don't care much for the way prettier formats my code....

**Comment by mariuslundgard** [comment]
Same here, the formatting is not my personal taste. But I like the idea ([refmt](https://facebook.github.io/reason/tools.html)), and probably could get used to it.

**Comment by popeindustries** [comment]
Ha ha. I almost didn't notice. Thought it wasn't working. The `nrk` ruleset on the other hand...

**Comment by mariuslundgard** [comment]
@popeindustries This is not the place for bashing. Instead explain what you don't like in another issue.

**Comment by popeindustries** [comment]
No harm intended. Just surprised is all

**Comment by mariuslundgard** [comment]
Some interesting tools:
https://atom.io/packages/prettier-atom (has `prettier-eslint`)
https://github.com/prettier/prettier-eslint-cli (cli-version of `prettier-eslint`)
... in combination with `husky` and `lint-staged`.

I successfully setup auto-formatting in Atom, based on stylistic rules from `.eslintrc`. So there's no lock-in to using `prettier`'s default style.

**Comment by cristobal** [comment]
eslint-config-nrk has served its purpose, and time has come to externalize updated linter config to other projects. NRK teams are recommended to use standard.js (with corresponding editor plugins).
