### ISSUE TITLE
Base support should be for ES5, with ES2015 as an extension

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/eslint-config-nrk#5]
Currently only ES6 code is supported out-of-the-box.

A possible solution is doing something like this:

```json
{
  "extends": [
    "nrk",
    "nrk/rules/es6"
  ]
}
```

---

Alternatively, for ES5:

```json
{
  "extends": [
    "nrk/rules/core"
  ]
}
```

And for ES6:

```json
{
  "extends": [
    "nrk"
  ]
}
```

**Comment by janerikbr** [comment]
Assuming most people use `es6` these days, we will keep supporting that version out of the box by using extends `nrk`:

```
{
  extends: [
    'nrk'
  ]
}
```

However, in an upcoming version, we will attempt to support `es5` enviroments by extending `nrk/es5`, like this:

```
{
  extends: [
    'nrk/es5'
  ]
}
```
