### ISSUE TITLE
Relax arrow-parens

### ISSUE THREAD

**Issue by svenanders** [nrkno/eslint-config-nrk#53]
Code such as ```export default input => Math.pow(input, input);``` should be allowed. No need to enforce parens.

**Comment by mariuslundgard** [comment]
Yes, I agree, if most of us now feel comfortable with arrow functions. It was my idea originally, and the arguments were:

Visual consistency:

```js
const a = b => b + 1
const a = (b, c) => b + c
// Would be great to be able to:
// const a = b => b + 1
// const a = b c => b + c
```

Avoid confusion between functions and assignments (in other words, functions that are hard to distinguish as functions):

```js
const a = b => b + 1
const a = b + 1
```

Could you make a PR @svenanders?

**Comment by svenanders** [comment]
Visual consistency is good and I'd also love to be able to write ```const x = y z => y + z``` or ```new Promise(reject, resolve => {...})```, but i guess that's not in the cards. I love being able to skip the parens, as it makes the functions more visually appealing, but then again, you'll often end up having to add parens when introducing more args.

My understanding is that this rule is included to avoid confusion for less experienced programmers, but it does come with a price:

 - having to add parens for single-arg functions (annoying)
 - mentally parsing unnecessary parens. Eslint should maybe have a _no-unnecessary-parens_ rule, to enforce this (if nothing else then for the educational value).

I am of the same mind with regards to semicolons. I know semicolons are commonly used to terminate statements, but they don't actually terminate, they separate. You only need semicolons when you have two statements on the same line, or you when you define an assignment statement. I'm 100% in favor of removing the semi rule.

**Comment by cristobal** [comment]
Well `const x = y z => y + z`  is not supported :/

I think we can loosen a bit by using the following options:

```
"arrow-parens": ["2", "as-needed", { "requireForBlockBody": true }]
```

If you really want to turn it off you can do it in your `.eslintrc` settings but by default i would not recommend us to change this in our settings, as the case when there is more than one argument.

**Comment by mariuslundgard** [comment]
Yes, basically I wanted us to enforce parens to avoid confusion for the less experienced in our ranks. NRK has many levels of JS developers at this point.

Perhaps it's an overly nice gesture (and condescending to others). Quite a few rules are based on the idea of *inclusion*; something like **“`eslint-config-nrk` should enforce good practices and a style that is readable and approachable to as many as possible”**. But if that gets in the way of productivity and peace of mind for the more experienced developers, that's a pity and something to take into account.

Idea: Run an anonymous poll to test which JS features people use and are comfortable with, among the developers at NRK.

You have reasonable points @svenanders and @cristobal – let's try to get a few more people's opinions somehow. I think this issue and discussion is quite a fundamental one, and `arrow-parens` is just one manifestation.

**Comment by mariuslundgard** [comment]
https://www.poll-maker.com/poll1025804x698E4986-43

Could we post this on #frontend, or is it weirst?

**Comment by cristobal** [comment]
@mariuslundgard feels weird and mostly end in a large rant.

Wwith the settings above @svenanders would actually get what he wishes for. I would argue against turning it completely off e.g.:

```
const z = x, y =>  x + y
```

vs.

```
const z = (x, y) => x + y
```

Is more concise having parens here makes it visually easier to see that it actually is a function, when just scrolling in the code.

The other part is if one uses:

```
const fn = x, y => { x * y  }
```

It's not easy to tell whether it's an function or a block scope, since we have many developer that are not JS developer and many other PL implement block scope however this is not the case for JS. 
The `{ "requireForBlockBody": true }` is copied from the Airbnb JS Styleguide https://github.com/airbnb/javascript#arrows--one-arg-parens.

**Comment by cristobal** [comment]
eslint-config-nrk has served its purpose, and time has come to externalize updated linter config to other projects. NRK teams are recommended to use standard.js (with corresponding editor plugins).
