### ISSUE TITLE
Relax semi

### ISSUE THREAD

**Issue by svenanders** [nrkno/eslint-config-nrk#54]
This issue is a spinout from #53  

The enforced semicolon rule is understandable in a historic sense (since a lot of JS "thought leaders" have championed the use of them), but it's a fact that semis are ultimately not necessary in JavaScript except when terminating statements on a single line (which is usually a bad idea anyway) and at the end of an assignment statement. 

Code Academy has a good writeup of when to use them here: https://www.codecademy.com/en/forum_questions/507f6dd09266b70200000d7e

I propose to relax this into either them being not required at all (preferred) or at least only issuing a warning when they're omitted rather than a throwing a hard error.

**Comment by mariuslundgard** [comment]
I'm pro no-semi, but this is a tricky debate.

Some historic reference: `eslint-config-nrk` was originally configured with `"semi": [2, "never"]` before PR https://github.com/nrkno/eslint-config-nrk/pull/1.

**Comment by cristobal** [comment]
I would suggest the following:

1. `"semi": [1, "never"]` (warning)
2. `"no-unexpected-multiline": "error"
3. Perhaps we need to tune  `space-unary-ops` and `func-call-spacing` (don't think so will look into tit)

**Comment by mariuslundgard** [comment]
https://feross.org/never-use-semicolons/

**Comment by svenanders** [comment]
Good point

> There are actually many more “edge cases” to keep in mind with “always use semicolons” than with “never use semicolons”.

**Comment by idrougge** [comment]
If the linter can discover where it expects a semicolon, the parser can do that as well and go on parsing. Semicolons are just line noise.

**Comment by cristobal** [comment]
eslint-config-nrk has served its purpose, and time has come to externalize updated linter config to other projects. NRK teams are recommended to use standard.js (with corresponding editor plugins).

**Comment by idrougge** [comment]
Burn in hell, eslint-config-nrk
